"""changed username properties

Revision ID: 068abd24039a
Revises: ca82412a1231
Create Date: 2020-12-02 09:57:49.806573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068abd24039a'
down_revision = 'ca82412a1231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Users_username', table_name='Users')
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.create_index('ix_Users_username', 'Users', ['username'], unique=True)
    # ### end Alembic commands ###
