"""altered the files model datateCreated and dateAuthorized columns

Revision ID: 2d7c62bc62ab
Revises: 7848cb1a014c
Create Date: 2021-04-19 13:13:42.202815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d7c62bc62ab'
down_revision = '7848cb1a014c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Files', 'dateCreated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Files', sa.Column('dateCreated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
