"""changed the type of mobile from integer to string

Revision ID: 36825abe2d60
Revises: 41adb80ce1ac
Create Date: 2021-04-08 16:00:07.782982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36825abe2d60'
down_revision = '41adb80ce1ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Employees', 'mobile',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Employees', 'mobile',
               existing_type=sa.String(length=12),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
