"""added a project status column

Revision ID: 66489d22459f
Revises: 2054518b307d
Create Date: 2021-04-30 12:59:08.674180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66489d22459f'
down_revision = '2054518b307d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Project', sa.Column('project_status', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Project', 'project_status')
    # ### end Alembic commands ###
