"""adding the project model

Revision ID: 68be880f1f35
Revises: 8f5db5129e7d
Create Date: 2020-10-01 11:18:36.865443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68be880f1f35'
down_revision = '8f5db5129e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('companyId', sa.Integer(), nullable=True),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['companyId'], ['Company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Project')
    # ### end Alembic commands ###
