"""creating the files model

Revision ID: 70e43dc69dc4
Revises: 75c4ede97e36
Create Date: 2020-10-01 13:25:25.880284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e43dc69dc4'
down_revision = '75c4ede97e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=120), nullable=False),
    sa.Column('companyId', sa.Integer(), nullable=True),
    sa.Column('projectId', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('date_reviewed', sa.DateTime(), nullable=True),
    sa.Column('authorized_by', sa.Integer(), nullable=True),
    sa.Column('date_authorized', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['companyId'], ['Company.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name')
    )
    op.add_column('Employees', sa.Column('projectId', sa.Integer(), nullable=True))
    op.drop_constraint('Employees_project_fkey', 'Employees', type_='foreignkey')
    op.create_foreign_key(None, 'Employees', 'Project', ['projectId'], ['id'])
    op.drop_column('Employees', 'project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Employees', sa.Column('project', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Employees', type_='foreignkey')
    op.create_foreign_key('Employees_project_fkey', 'Employees', 'Project', ['project'], ['id'])
    op.drop_column('Employees', 'projectId')
    op.drop_table('Files')
    # ### end Alembic commands ###
