"""creating the files table

Revision ID: 92d74c965e5f
Revises: c4464defebf6
Create Date: 2021-04-13 11:27:55.840959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d74c965e5f'
down_revision = 'c4464defebf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Files',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('companyId', sa.String(length=20), nullable=True),
    sa.Column('projectId', sa.String(length=20), nullable=True),
    sa.Column('createdBy', sa.String(length=20), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), nullable=True),
    sa.Column('authorizedBy', sa.String(length=20), nullable=True),
    sa.Column('dateAuthorizedOrRejected', sa.DateTime(), nullable=True),
    sa.Column('fileStatus', sa.String(length=25), nullable=False),
    sa.Column('fileUrl', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['authorizedBy'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['companyId'], ['Company.id'], ),
    sa.ForeignKeyConstraint(['createdBy'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Files')
    # ### end Alembic commands ###
