"""recreating the db

Revision ID: 9428a84fbfd9
Revises: 
Create Date: 2020-11-20 23:04:12.260704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9428a84fbfd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=64), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('companyId', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=25), nullable=False),
    sa.Column('isActive', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['companyId'], ['Company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Company_company'), 'Company', ['company'], unique=True)
    op.create_table('Project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('companyId', sa.Integer(), nullable=True),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['companyId'], ['Company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_name')
    )
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=True)
    op.create_table('Budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyId', sa.Integer(), nullable=True),
    sa.Column('projectId', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['companyId'], ['Company.id'], ),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('companyId', sa.Integer(), nullable=True),
    sa.Column('projectId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['companyId'], ['Company.id'], ),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=120), nullable=False),
    sa.Column('companyId', sa.Integer(), nullable=True),
    sa.Column('projectId', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('date_reviewed', sa.DateTime(), nullable=True),
    sa.Column('authorized_by', sa.Integer(), nullable=True),
    sa.Column('date_authorized', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['companyId'], ['Company.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Files')
    op.drop_table('Employees')
    op.drop_table('Budget')
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_table('Users')
    op.drop_table('Project')
    op.drop_index(op.f('ix_Company_company'), table_name='Company')
    op.drop_table('Company')
    # ### end Alembic commands ###
