"""changed firstname field to username

Revision ID: b68d0e58fcab
Revises: 70e43dc69dc4
Create Date: 2020-10-23 12:39:53.992581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68d0e58fcab'
down_revision = '70e43dc69dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=True)
    op.drop_index('ix_Users_firstname', table_name='Users')
    op.drop_column('Users', 'firstname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('firstname', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_Users_firstname', 'Users', ['firstname'], unique=False)
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.drop_column('Users', 'username')
    # ### end Alembic commands ###
