"""create employees table

Revision ID: bb9e04654e99
Revises: f305bf6150c4
Create Date: 2021-01-19 08:34:28.639673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb9e04654e99'
down_revision = 'f305bf6150c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Employees',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('mobile', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('companyId', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['companyId'], ['Company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Employees')
    # ### end Alembic commands ###
