"""running migrations a fresh

Revision ID: bc95666c38c3
Revises: 9428a84fbfd9
Create Date: 2020-11-21 18:44:17.091254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc95666c38c3'
down_revision = '9428a84fbfd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Budget')
    op.drop_table('Files')
    op.drop_table('Project')
    op.drop_table('Employees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Employees',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Employees_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('companyId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('projectId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['companyId'], ['Company.id'], name='Employees_companyId_fkey'),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], name='Employees_projectId_fkey'),
    sa.PrimaryKeyConstraint('id', name='Employees_pkey')
    )
    op.create_table('Project',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Project_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('companyId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_to', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['companyId'], ['Company.id'], name='Project_companyId_fkey'),
    sa.PrimaryKeyConstraint('id', name='Project_pkey'),
    sa.UniqueConstraint('project_name', name='Project_project_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Files',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Files_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('companyId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('projectId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_reviewed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('authorized_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_authorized', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['authorized_by'], ['Users.id'], name='Files_authorized_by_fkey'),
    sa.ForeignKeyConstraint(['companyId'], ['Company.id'], name='Files_companyId_fkey'),
    sa.ForeignKeyConstraint(['created_by'], ['Users.id'], name='Files_created_by_fkey'),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], name='Files_projectId_fkey'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['Users.id'], name='Files_reviewed_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='Files_pkey'),
    sa.UniqueConstraint('file_name', name='Files_file_name_key')
    )
    op.create_table('Budget',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Budget_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('companyId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('projectId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['companyId'], ['Company.id'], name='Budget_companyId_fkey'),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], name='Budget_projectId_fkey'),
    sa.PrimaryKeyConstraint('id', name='Budget_pkey')
    )
    # ### end Alembic commands ###
