"""removed file url from budget table

Revision ID: c4464defebf6
Revises: 36825abe2d60
Create Date: 2021-04-11 13:16:22.637844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4464defebf6'
down_revision = '36825abe2d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Budget_fileUrl_key', 'Budget', type_='unique')
    op.drop_column('Budget', 'fileUrl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Budget', sa.Column('fileUrl', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.create_unique_constraint('Budget_fileUrl_key', 'Budget', ['fileUrl'])
    # ### end Alembic commands ###
