"""changed username properties

Revision ID: cacb5738f7d5
Revises: 068abd24039a
Create Date: 2020-12-02 10:02:14.665748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cacb5738f7d5'
down_revision = '068abd24039a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Users_username', table_name='Users')
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.create_index('ix_Users_username', 'Users', ['username'], unique=False)
    # ### end Alembic commands ###
