"""creating the detailedFile table

Revision ID: fdfdb3d7f35b
Revises: 4b14beecef5a
Create Date: 2021-05-20 16:13:55.718016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdfdb3d7f35b'
down_revision = '4b14beecef5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DetailedFile',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('companyId', sa.String(length=20), nullable=True),
    sa.Column('projectId', sa.String(length=20), nullable=True),
    sa.Column('fileType', sa.String(length=20), nullable=False),
    sa.Column('urbanLocalTransport', sa.Float(), nullable=True),
    sa.Column('briefingLocalTransport', sa.Float(), nullable=True),
    sa.Column('ruralLocalTransport', sa.Float(), nullable=True),
    sa.Column('periUrbanLocalTransport', sa.Float(), nullable=True),
    sa.Column('interviewerWage', sa.Float(), nullable=True),
    sa.Column('tl_sup_wage', sa.Float(), nullable=True),
    sa.Column('rc_wage', sa.Float(), nullable=True),
    sa.Column('interviewersAllowance', sa.Float(), nullable=True),
    sa.Column('tl_sup_rc_allowance', sa.Float(), nullable=True),
    sa.Column('briefingHighwayTransport', sa.Float(), nullable=True),
    sa.Column('interTownHighwayTransport', sa.Float(), nullable=True),
    sa.Column('interviewerTelephone', sa.Float(), nullable=True),
    sa.Column('tl_sup_rc_telephone', sa.Float(), nullable=True),
    sa.Column('printingCost', sa.Float(), nullable=True),
    sa.Column('covid19Masks', sa.Float(), nullable=True),
    sa.Column('covid19Sanitizers', sa.Float(), nullable=True),
    sa.Column('briefingRefreshments', sa.Float(), nullable=True),
    sa.Column('briefingHallHire', sa.Float(), nullable=True),
    sa.Column('fieldWorkHallHire', sa.Float(), nullable=True),
    sa.Column('totalAmount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['companyId'], ['Company.id'], ),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DetailedFile')
    # ### end Alembic commands ###
